### ISSUE TITLE
CBT 0.1,0.2 下載鏈接補充

### ISSUE THREAD

**Issue by DuolaD** [360NENZ/ZZZ-Download-Library#2]
英雄形態的哆啦D夢|DuolaD再次登場！

据測試很多鏈接均已失效，那我就來補鏈接咯。

記得在Readme.md裏寫一下"Provide By [哆啦D夢|DuolaD](https://github.com/DuolaD)和[CYTeam](https://www.cyteam.cn/)"
（沒錯這個也要）
因爲是他們的微軟開發者域。

## 

ZZZ CBT 0.10 PC:

Launcher:
[CN](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EcnvwuIBpRlLnmCsy02qzakBpSe6YWsLlZNDJh2HZ0lgxQ?e=aL3bo7)
[OS](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/ESOGXM9E9HhJhG4NrveGX6cB8vTayPah3PsDudemCHoYVw?e=jE3Zky)

Client:
[CN](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/ETMawhfd0kdDm0Y1KrcMFkEBIY8qHsdNtiy0bL9sMP2wdg?e=S0TNWM)
[OS](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/ESn3PYW0bG5CrgibNoauOVwBNkeVIrgh3aG42fZ79gDrvQ?e=rjmbd6)

Character Voice(Not Audio):
[Chinese](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EbZ3SFZH-fZBuJsvU4bshg0BC-BlHgS9Q42HdGW0ZJxTaA?e=ptDmjm)

OST:
[Download link](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EaK4bdMid-5DhhpBz1TrKTcB4UaM6h4Wj4UYQwaLGFQOjg?e=PchTvk)

## 

ZZZ CBT 0.20 PC:

Launcher:
[CN](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/Edj5Vq4_G75OnFoKA1Rji-ABlUEe3I9qapRG-K0mc_0xAw?e=iQzeq8)
[OS](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/ESdCteGArwRHg_hv8PyqVx0BTFCp1KBH8CouXA3aOwaaLg?e=zMHoUF)

Client:
[CN](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/Ea4z_HaV_llLmhrpZYyNFfUB_C0aH5JopFCqB-8CDNljKg?e=ezzgf0)
[OS](https://7ww2hb-my.sharepoint.com/:u:/g/personal/duolad_cyteam_me/EchDZ_be9sBInszUfSubLW4B9KB1YU4cPSvDM5CP_6U8zg?e=pGaNQ3)

**Comment by DuolaD** [comment]
LMAO

**Comment by 360NENZ** [comment]
pr directly（
don't use issue（

**Comment by DuolaD** [comment]
> pr directly（ don't use issue（

lazy lmao()

**Comment by 360NENZ** [comment]
lazy too（）

**Comment by DuolaD** [comment]
ok

> lazy too（）

OK(),I will PR

**Comment by DuolaD** [comment]
https://github.com/360NENZ/ZZZ-Download-Library/pull/3

@360NENZ Done

**Comment by 360NENZ** [comment]
merged
